rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-assembly/eagle-assembly.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-assembly/alert-assembly.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-common/alert-common.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-coordinator/alert-coordinator.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-devtools/alert-devtools.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-engine/alert-engine.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-metadata-parent/alert-metadata/alert-metadata.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-metadata-parent/alert-metadata-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-metadata-parent/alert-metadata-service/alert-metadata-service.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/alert-service/alert-service.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert/eagle-alert.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert-app/eagle-alert-app.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-alert-parent/eagle-alert-service/eagle-alert-service.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-app/eagle-app-base/eagle-app-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-app/eagle-app-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-app/eagle-app-streamproxy/eagle-app-streamproxy.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-app/eagle-app-utils/eagle-app-utils.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-common/eagle-common.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-core.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-data-process/eagle-data-process.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-embed/eagle-embed-hbase/eagle-embed-hbase.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-embed/eagle-embed-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-embed/eagle-embed-server/eagle-embed-server.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-metadata/eagle-metadata-base/eagle-metadata-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-metadata/eagle-metadata-jdbc/eagle-metadata-jdbc.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-metadata/eagle-metadata-mongo/eagle-metadata-mongo.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-metadata/eagle-metadata.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-metric/eagle-metric.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-antlr/eagle-antlr.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-audit-base/eagle-audit-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-client-base/eagle-client-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-entity-base/eagle-entity-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-query-base/eagle-query-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-query-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-service-base/eagle-service-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-storage-base/eagle-storage-base.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-storage-hbase/eagle-storage-hbase.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-core/eagle-query/eagle-storage-jdbc/eagle-storage-jdbc.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-examples/eagle-app-example/eagle-app-example.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-examples/eagle-examples.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-external/eagle-cdh/eagle-cdh.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-external/eagle-external-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-external/eagle-kafka/eagle-kafka.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-external/eagle-log4jkafka/eagle-log4jkafka.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-gc/eagle-gc.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-hadoop-queue/eagle-hadoop-queue.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-aggregation/eagle-jpm-aggregation.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-analyzer/eagle-jpm-analyzer.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-entity/eagle-jpm-entity.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-mr-history/eagle-jpm-mr-history.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-mr-running/eagle-jpm-mr-running.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-service/eagle-jpm-service.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-spark-history/eagle-jpm-spark-history.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-spark-running/eagle-jpm-spark-running.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-util/eagle-jpm-util.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-jpm/eagle-jpm-web/eagle-jpm-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-metric/eagle-hadoop-metric/eagle-hadoop-metric.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-metric/eagle-hbase-web/eagle-hbase-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-metric/eagle-hdfs-web/eagle-hdfs-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-metric/eagle-metric-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-metric/eagle-system-web/eagle-system-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-metric-collection/eagle-metric-collection.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-common/eagle-security-common.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-hbase-auditlog/eagle-security-hbase-auditlog.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-hbase-web/eagle-security-hbase-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-hdfs-auditlog/eagle-security-hdfs-auditlog.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-hdfs-authlog/eagle-security-hdfs-authlog.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-hdfs-web/eagle-security-hdfs-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-hive/eagle-security-hive.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-hive-web/eagle-security-hive-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-maprfs-auditlog/eagle-security-maprfs-auditlog.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-maprfs-web/eagle-security-maprfs-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-oozie-auditlog/eagle-security-oozie-auditlog.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-oozie-web/eagle-security-oozie-web.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-security/eagle-security-parent.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-server/eagle-server.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-server/src/main/webapp/app/node_modules/angular-ui-router/ui-router2.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-topology-assembly/eagle-topology-assembly.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-topology-check/eagle-topology-app/eagle-topology-app.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-topology-check/eagle-topology-check.iml
rm -f /Users/mazhiyong/open-code/github/apache-eagle-0.5.0/eagle-topology-check/eagle-topology-entity/eagle-topology-entity.iml
